FROM microsoft/dotnet:2.1-sdk
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["TcpMux/TcpMux.csproj", "TcpMux/"]

RUN dotnet restore "TcpMux/TcpMux.csproj"
COPY . .
WORKDIR "/src/TcpMux"
RUN dotnet build --no-restore "TcpMux.csproj" -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-restore", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]